{
    'name': 'Repair Shop Tickets',
    'version': '19.0.1.0.0',
    'category': 'Services/Field Service',
    'summary': 'Manage repair jobs, parts, invoices & receipts',
    'author': 'Punished_Snake',
    'website': '',
    'license': 'OPL-1',
    'depends': ['base', 'product', 'account', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'report/service_ticket_receipt.xml',
        'views/service_ticket_views.xml',
        'views/service_ticket_menus.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
}
